#!/usr/bin/env python3
"""Generate compact Markdown catalog and evidence-coverage views."""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ROWS = json.loads((ROOT / "data" / "papers.json").read_text())
ROWS.sort(key=lambda row: (-row["year"], row["title"].lower()))


def compact(values: list[str]) -> str:
    return ", ".join(f"`{value}`" for value in values)


def write_catalog() -> None:
    lines = [
        "# Catalog\n",
        "<!-- Generated by scripts/generate_views.py; do not edit manually. -->\n",
        f"Current snapshot: **{len(ROWS)} records**. Use the [interactive Atlas](https://rainiver.github.io/constrained-decoding-atlas/) for combined filters.\n",
        "| Year | Work | Type | Specification | Placement | Evidence |",
        "|---:|---|---|---|---|---|",
    ]
    for row in ROWS:
        title = row["title"].replace("|", "\\|")
        lines.append(
            f"| {row['year']} | [{title}]({row['url']}) | {compact(row['study_type'])} | "
            f"{compact(row['specification'])} | {compact(row['placement'])} | `{row['review_status']}` |"
        )
    (ROOT / "docs" / "catalog.md").write_text("\n".join(lines) + "\n")


def section(title: str, field: str) -> list[str]:
    counts = Counter(label for row in ROWS for label in row[field])
    meaningful = [(label, count) for label, count in counts.most_common() if label != "not_reported"]
    missing = counts.get("not_reported", 0)
    lines = [f"## {title}\n", "| Label | Papers | Coverage |", "|---|---:|---:|"]
    for label, count in meaningful:
        lines.append(f"| `{label}` | {count} | {count / len(ROWS):.0%} |")
    if missing:
        lines.append(f"| `not_reported` | {missing} | {missing / len(ROWS):.0%} |")
    return lines


def write_coverage() -> None:
    peer = sum(row["publication_status"] == "peer_reviewed" for row in ROWS)
    screened = sum(row["review_status"] != "metadata_verified" for row in ROWS)
    with_code = sum(bool(row["code_url"]) for row in ROWS)
    lines = [
        "# Evidence Coverage\n",
        "<!-- Generated by scripts/generate_views.py; do not edit manually. -->\n",
        "This page reports what the current Atlas records—not the prevalence of properties in the entire field. The corpus and evidence depth are still expanding.\n",
        "| Snapshot statistic | Count | Share |",
        "|---|---:|---:|",
        f"| Records | {len(ROWS)} | 100% |",
        f"| Peer reviewed | {peer} | {peer / len(ROWS):.0%} |",
        f"| Full text screened or coded | {screened} | {screened / len(ROWS):.0%} |",
        f"| Linked code artifact | {with_code} | {with_code / len(ROWS):.0%} |",
        "",
    ]
    lines += section("Constraint specifications", "specification") + [""]
    lines += section("Enforcement placement", "placement") + [""]
    lines += section("Guarantees claimed or established", "guarantees") + [""]
    lines += section("Systems measurements", "systems_measurements") + [""]
    lines += section("Outcome measurements", "outcome_measurements") + [""]
    (ROOT / "docs" / "coverage.md").write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    write_catalog()
    write_coverage()
    print(f"Generated Markdown views for {len(ROWS)} records")
