#!/usr/bin/env python3
"""Generate the compact README inventory from the machine-readable catalog."""

from __future__ import annotations

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ROWS = json.loads((ROOT / "data" / "papers.json").read_text())
ROWS.sort(key=lambda row: (-row["year"], row["title"].lower()))


FRONTIER_SPECS = {"state", "policy", "relation"}
SHORT = {
    "regex_fsm": "FSM",
    "cfg_parser": "CFG",
    "pda": "PDA",
    "trie": "trie",
    "token_index": "token index",
    "programmatic": "program",
    "solver": "solver",
    "membership_oracle": "oracle",
    "classifier": "classifier",
    "framework_dependent": "varies",
    "provider_undisclosed": "undisclosed",
    "multi_stage": "multi-stage",
    "sequence": "sequence",
    "token": "token",
    "field": "field",
    "not_reported": "—",
}


def label(values: list[str], limit: int = 3) -> str:
    seen = [SHORT.get(v, v.replace("_", " ")) for v in values]
    head, extra = seen[:limit], len(seen) - limit
    return ", ".join(head) + (f" +{extra}" if extra > 0 else "")


def display_title(title: str) -> str:
    """Keep tables scannable: drop the subtitle when the full title is long."""
    if len(title) > 58 and ":" in title:
        head = title.split(":", 1)[0].strip()
        if len(head) >= 8:
            return head
    return title


def rows_table(rows: list[dict]) -> list[str]:
    out = [
        "| Year | Work | Constrains | Enforced at | Represented as |",
        "|---:|---|---|---|---|",
    ]
    reviewed = {"full_text_screened", "full_text_coded", "second_pass_verified"}
    for row in rows:
        title = display_title(row["title"]).replace("|", "\\|")
        venue = row["venue"]
        suffix = f" · {venue}" if venue and venue != "arXiv" else ""
        full_text_mark = " †" if row["review_status"] in reviewed else ""
        out.append(
            f"| {row['year']} | [{title}]({row['url']}){full_text_mark}{suffix} | "
            f"{label(row['specification'])} | {label(row['placement'])} | "
            f"{label(row['representation'])} |"
        )
    return out


SPEC_ROWS = [
    ("Syntax", "syntax"),
    ("Schema", "schema"),
    ("Semantics", "semantic"),
    ("Lexical", "lexical"),
    ("Types", "type"),
    ("Relations across fields", "relation"),
    ("**Mutable world state**", "state"),
    ("**Policy / authorization**", "policy"),
]
PLACE_ROWS = [
    ("Token", "token"),
    ("Multi-stage", "multi_stage"),
    ("Completed sequence", "sequence"),
    ("**Field / span**", "field"),
]


def count(field: str, value: str) -> int:
    return sum(1 for row in ROWS if value in row[field])


def write_readme_stats() -> None:
    readme = ROOT / "README.md"
    text = readme.read_text()
    start, end = "<!-- STATS:START -->", "<!-- STATS:END -->"
    if start not in text or end not in text:
        raise SystemExit("README is missing STATS markers")

    n = len(ROWS)
    fully_coded = sum(row["review_status"] in {"full_text_coded", "second_pass_verified"} for row in ROWS)
    screened = sum(row["review_status"] == "full_text_screened" for row in ROWS)
    reviewed = fully_coded + screened

    def cell(label: str, field: str, value: str) -> str:
        c = count(field, value)
        return f"| {label} | {c} ({c / n:.0%}) "

    left = [cell(lbl, "specification", key) for lbl, key in SPEC_ROWS]
    right = [cell(lbl, "placement", key) for lbl, key in PLACE_ROWS]
    right += [
        "| | ",
        "| **What happens to a rejected token** | ",
        f"| Masked or pruned | {count('rejected_behavior', 'mask') + count('rejected_behavior', 'prune')} ",
        f"| Resampled or regenerated | {count('rejected_behavior', 'resample') + count('rejected_behavior', 'regenerate')} ",
        f"| **Repaired in place** | **{count('rejected_behavior', 'repair')}** ",
    ]
    pad = max(len(left), len(right))
    left += ["| | "] * (pad - len(left))
    right += [""] * (pad - len(right))

    body = [
        start,
        "<!-- Generated by scripts/generate_views.py; edit data/papers.json instead. -->",
        "",
        "| What gets constrained | Papers | | Where enforcement acts | Papers |",
        "|---|---:|---|---|---:|",
    ]
    for lhs, rhs in zip(left, right):
        body.append(f"{lhs}|{rhs or '| '}|")
    body += [
        "",
        f"**Catalog signal:** {count('specification', 'syntax')}/{n} works constrain syntax and "
        f"{count('placement', 'token')}/{n} intervene token by token, while only "
        f"{count('specification', 'state')} model mutable state, "
        f"{count('specification', 'relation')} cross-field relations, "
        f"{count('specification', 'policy')} policy or authorization, and "
        f"{count('rejected_behavior', 'repair')} in-place repair.",
        "",
        f"*Boundary: {reviewed} papers have been checked against full text; the inventory also "
        "includes provisional discovery records. Counts describe this catalog, not field-wide prevalence.*",
        "",
        end,
    ]

    head, _, rest = text.partition(start)
    _, _, tail = rest.partition(end)
    text = head + "\n".join(body) + tail

    text = re.sub(
        r"full--text%20reviewed-\d+%2F\d+",
        f"full--text%20reviewed-{reviewed}%2F{n}",
        text,
    )
    text = re.sub(r"catalog-\d+%20papers", f"catalog-{n}%20papers", text)
    # Header subtitle sits outside the generated blocks; keep its counts honest.
    text = re.sub(
        r"^\d+ papers · \d+ read in full",
        f"{n} papers · {reviewed} read in full",
        text,
        flags=re.MULTILINE,
    )
    readme.write_text(text)


def write_readme_catalog() -> None:
    readme = ROOT / "README.md"
    text = readme.read_text()
    start, end = "<!-- CATALOG:START -->", "<!-- CATALOG:END -->"
    if start not in text or end not in text:
        raise SystemExit("README is missing CATALOG markers")

    frontier = [r for r in ROWS if FRONTIER_SPECS & set(r["specification"])]
    body = [
        start,
        "<!-- Generated by scripts/generate_views.py; edit data/papers.json instead. -->",
        "",
        "† checked against full text; unmarked discovery records have metadata and link verification only. "
        "Detailed evidence status remains available in the filters and JSON data.",
        "",
        "### The frontier: constraints that depend on state, relations, or policy",
        "",
        f"Works addressing state-, relation-, or policy-dependent constraints. "
        f"{len(frontier)} of {len(ROWS)} records.",
        "",
    ]
    body += rows_table(frontier)
    body += [
        "",
        "### Full catalog",
        "",
        f"All {len(ROWS)} records, newest first.",
        "",
    ]
    body += rows_table(ROWS)
    body += ["", end]

    head, _, rest = text.partition(start)
    _, _, tail = rest.partition(end)
    readme.write_text(head + "\n".join(body) + tail)


if __name__ == "__main__":
    write_readme_stats()
    write_readme_catalog()
    print(f"Generated Markdown views for {len(ROWS)} records")
