#!/usr/bin/env python3
"""Generate compact Markdown catalog and evidence-coverage views."""

from __future__ import annotations

import json
import re
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ROWS = json.loads((ROOT / "data" / "papers.json").read_text())
ROWS.sort(key=lambda row: (-row["year"], row["title"].lower()))


def compact(values: list[str]) -> str:
    return ", ".join(f"`{value}`" for value in values)


def write_catalog() -> None:
    lines = [
        "# Catalog\n",
        "<!-- Generated by scripts/generate_views.py; do not edit manually. -->\n",
        f"Current snapshot: **{len(ROWS)} records**. Use the [interactive Atlas](https://rainiver.github.io/constrained-decoding-atlas/) for combined filters.\n",
        "| Year | Work | Type | Specification | Placement | Evidence |",
        "|---:|---|---|---|---|---|",
    ]
    for row in ROWS:
        title = row["title"].replace("|", "\\|")
        lines.append(
            f"| {row['year']} | [{title}]({row['url']}) | {compact(row['study_type'])} | "
            f"{compact(row['specification'])} | {compact(row['placement'])} | `{row['review_status']}` |"
        )
    (ROOT / "docs" / "catalog.md").write_text("\n".join(lines) + "\n")


def section(title: str, field: str) -> list[str]:
    counts = Counter(label for row in ROWS for label in row[field])
    meaningful = [(label, count) for label, count in counts.most_common() if label != "not_reported"]
    missing = counts.get("not_reported", 0)
    lines = [f"## {title}\n", "| Label | Papers | Coverage |", "|---|---:|---:|"]
    for label, count in meaningful:
        lines.append(f"| `{label}` | {count} | {count / len(ROWS):.0%} |")
    if missing:
        lines.append(f"| `not_reported` | {missing} | {missing / len(ROWS):.0%} |")
    return lines


def write_coverage() -> None:
    peer = sum(row["publication_status"] == "peer_reviewed" for row in ROWS)
    screened = sum(row["review_status"] != "metadata_verified" for row in ROWS)
    with_code = sum(bool(row["code_url"]) for row in ROWS)
    lines = [
        "# Evidence Coverage\n",
        "<!-- Generated by scripts/generate_views.py; do not edit manually. -->\n",
        "This page reports what the current Atlas records—not the prevalence of properties in the entire field. The corpus and evidence depth are still expanding.\n",
        "| Snapshot statistic | Count | Share |",
        "|---|---:|---:|",
        f"| Records | {len(ROWS)} | 100% |",
        f"| Peer reviewed | {peer} | {peer / len(ROWS):.0%} |",
        f"| Full text screened or coded | {screened} | {screened / len(ROWS):.0%} |",
        f"| Linked code artifact | {with_code} | {with_code / len(ROWS):.0%} |",
        "",
    ]
    lines += section("Constraint specifications", "specification") + [""]
    lines += section("Enforcement placement", "placement") + [""]
    lines += section("Guarantees claimed or established", "guarantees") + [""]
    lines += section("Systems measurements", "systems_measurements") + [""]
    lines += section("Outcome measurements", "outcome_measurements") + [""]
    (ROOT / "docs" / "coverage.md").write_text("\n".join(lines) + "\n")


FRONTIER_SPECS = {"state", "policy", "relation"}
SHORT = {
    "regex_fsm": "FSM",
    "cfg_parser": "CFG",
    "pda": "PDA",
    "trie": "trie",
    "token_index": "token index",
    "programmatic": "program",
    "solver": "solver",
    "membership_oracle": "oracle",
    "classifier": "classifier",
    "framework_dependent": "varies",
    "provider_undisclosed": "undisclosed",
    "multi_stage": "multi-stage",
    "sequence": "sequence",
    "token": "token",
    "field": "field",
    "not_reported": "—",
}


def label(values: list[str], limit: int = 3) -> str:
    seen = [SHORT.get(v, v.replace("_", " ")) for v in values]
    head, extra = seen[:limit], len(seen) - limit
    return ", ".join(head) + (f" +{extra}" if extra > 0 else "")


def display_title(title: str) -> str:
    """Keep tables scannable: drop the subtitle when the full title is long."""
    if len(title) > 58 and ":" in title:
        head = title.split(":", 1)[0].strip()
        if len(head) >= 8:
            return head
    return title


def rows_table(rows: list[dict]) -> list[str]:
    out = [
        "| | Year | Work | Constrains | Enforced at | Represented as |",
        "|:-:|---:|---|---|---|---|",
    ]
    for row in rows:
        mark = {
            "second_pass_verified": "●",
            "full_text_coded": "●",
            "full_text_screened": "◐",
            "metadata_verified": "○",
        }[row["review_status"]]
        title = display_title(row["title"]).replace("|", "\\|")
        venue = row["venue"]
        suffix = f" · {venue}" if venue and venue != "arXiv" else ""
        out.append(
            f"| {mark} | {row['year']} | [{title}]({row['url']}){suffix} | "
            f"{label(row['specification'])} | {label(row['placement'])} | "
            f"{label(row['representation'])} |"
        )
    return out


SPEC_ROWS = [
    ("Syntax", "syntax"),
    ("Schema", "schema"),
    ("Semantics", "semantic"),
    ("Lexical", "lexical"),
    ("Types", "type"),
    ("Relations across fields", "relation"),
    ("**Mutable world state**", "state"),
    ("**Policy / authorization**", "policy"),
]
PLACE_ROWS = [
    ("Token", "token"),
    ("Multi-stage", "multi_stage"),
    ("Completed sequence", "sequence"),
    ("**Field / span**", "field"),
]


def count(field: str, value: str) -> int:
    return sum(1 for row in ROWS if value in row[field])


def write_readme_stats() -> None:
    readme = ROOT / "README.md"
    text = readme.read_text()
    start, end = "<!-- STATS:START -->", "<!-- STATS:END -->"
    if start not in text or end not in text:
        raise SystemExit("README is missing STATS markers")

    n = len(ROWS)
    fully_coded = sum(row["review_status"] in {"full_text_coded", "second_pass_verified"} for row in ROWS)
    screened = sum(row["review_status"] == "full_text_screened" for row in ROWS)
    reviewed = fully_coded + screened

    def cell(label: str, field: str, value: str) -> str:
        c = count(field, value)
        return f"| {label} | {c} ({c / n:.0%}) "

    left = [cell(lbl, "specification", key) for lbl, key in SPEC_ROWS]
    right = [cell(lbl, "placement", key) for lbl, key in PLACE_ROWS]
    right += [
        "| | ",
        "| **What happens to a rejected token** | ",
        f"| Masked or pruned | {count('rejected_behavior', 'mask') + count('rejected_behavior', 'prune')} ",
        f"| Resampled or regenerated | {count('rejected_behavior', 'resample') + count('rejected_behavior', 'regenerate')} ",
        f"| **Repaired in place** | **{count('rejected_behavior', 'repair')}** ",
    ]
    pad = max(len(left), len(right))
    left += ["| | "] * (pad - len(left))
    right += [""] * (pad - len(right))

    body = [
        start,
        "<!-- Generated by scripts/generate_views.py; edit data/papers.json instead. -->",
        "",
        "| What gets constrained | Papers | | Where enforcement acts | Papers |",
        "|---|---:|---|---|---:|",
    ]
    for lhs, rhs in zip(left, right):
        body.append(f"{lhs}|{rhs or '| '}|")
    body += [
        "",
        f"*Current Atlas snapshot: {n} records; {fully_coded} fully coded, {screened} screened, "
        f"{n - reviewed} metadata-verified.* Token-time enforcement appears in "
        f"{count('placement', 'token')}/{n} records, while mutable state appears in "
        f"{count('specification', 'state')}/{n} and policy in "
        f"{count('specification', 'policy')}/{n}. These are catalog coverage gaps, not "
        "field-wide prevalence estimates.",
        "",
        end,
    ]

    head, _, rest = text.partition(start)
    _, _, tail = rest.partition(end)
    text = head + "\n".join(body) + tail

    text = re.sub(
        r"full--text%20reviewed-\d+%2F\d+",
        f"full--text%20reviewed-{reviewed}%2F{n}",
        text,
    )
    text = re.sub(r"catalog-\d+%20papers", f"catalog-{n}%20papers", text)
    readme.write_text(text)


def write_readme_catalog() -> None:
    readme = ROOT / "README.md"
    text = readme.read_text()
    start, end = "<!-- CATALOG:START -->", "<!-- CATALOG:END -->"
    if start not in text or end not in text:
        raise SystemExit("README is missing CATALOG markers")

    frontier = [r for r in ROWS if FRONTIER_SPECS & set(r["specification"])]
    body = [
        start,
        "<!-- Generated by scripts/generate_views.py; edit data/papers.json instead. -->",
        "",
        "### The frontier: constraints that depend on state, relations, or policy",
        "",
        f"Works addressing state-, relation-, or policy-dependent constraints. "
        f"{len(frontier)} of {len(ROWS)} records.",
        "",
    ]
    body += rows_table(frontier)
    body += [
        "",
        "### Full catalog",
        "",
        f"All {len(ROWS)} records, newest first. "
        "● fully coded · ◐ full text screened · ○ metadata verified.",
        "",
    ]
    body += rows_table(ROWS)
    body += ["", end]

    head, _, rest = text.partition(start)
    _, _, tail = rest.partition(end)
    readme.write_text(head + "\n".join(body) + tail)


if __name__ == "__main__":
    write_catalog()
    write_coverage()
    write_readme_stats()
    write_readme_catalog()
    print(f"Generated Markdown views for {len(ROWS)} records")
